version: '3'
services:
  website:
    network_mode: host
    container_name: website
    restart: always
    environment:
      - PORT=8080
      - NODE_ENV=develop
    build: ../front-end
    command: yarn dev-docker
    volumes:
      - ../front-end:/usr/app/
      - /usr/app/node_modules
    ports:
      - "8080:8080" 
  api:
    network_mode: host
    container_name: api
    restart: always
    build: ../api
    environment:
      - "TZ=America/Sao_Paulo"
    command: yarn dev
    volumes:
      - ../api:/usr/app/
      - /usr/app/node_modules
    ports:
      - "3001:3001"
    
  apigateway:
    network_mode: host
    container_name: api-gateway
    restart: always
    build: ../api-gateway
    command: yarn dev
    volumes:
      - ../api-gateway:/usr/app/
      - /usr/app/node_modules
    ports:
      - "3000:3000"
      
  admin:
    network_mode: host
    container_name: admin
    restart: always
    build: ../admin
    command: yarn dev
    environment:
      - PORT=8081
      - NODE_ENV=develop
    volumes:
      - ../admin:/usr/app/
      - /usr/app/node_modules
    ports:
      - "8081:8081"    
    depends_on:
      - apigateway
      - website
  landing:
    image: nginx:1.13
    container_name: landing-pages
    restart: always
    volumes:
      - "../landing-pages:/var/www/html"
      - "../landing-pages/config-nginx/lp:/etc/nginx/nginx.conf"
    ports:
      - "8800:8800"
    depends_on:
      - php

  # Application service layer
  php:
    container_name: php
    build:
      context: ../landing-pages/php
    volumes:
      - "../landing-pages:/var/www/html"
    ports:
      - "9000:9000"
  php-hotsite:
    container_name: php-hotsite
    build:
      context: ../hotsite/php
    volumes:
      - "../hotsite:/var/www/html"
    ports:
      - "9001:9000"
    networks: 
      - hotsite
    
  hotsite:
    image: nginx:1.13
    container_name: hotsite
    restart: always
    volumes:
      - "../hotsite:/var/www/html"
      - "../hotsite/config-nginx/lp:/etc/nginx/nginx.conf"
    ports:
      - "8082:8080"
    depends_on:
      - php-hotsite
    networks:
      - hotsite
      - phphot
  

networks:
  hotsite:
  phphot:
    driver_opts:
      foo: "1"
      bar: "2"
   
