version: '3'
services:
  website:
    network_mode: host
    container_name: website
    restart: always
    environment:
      - PORT=8080
      - NODE_ENV=develop
    build: ../front-end
    command: yarn dev-docker
    volumes:
      - ../front-end:/usr/app/
      - /usr/app/node_modules
    ports:
      - "8080:8080" 
  api:
    network_mode: host
    container_name: api
    build: ../api
    environment:
      - "TZ=America/Sao_Paulo"
    command: yarn dev
    volumes:
      - ../api:/usr/app/
      - /usr/app/node_modules
    ports:
      - "3001:3001"
    
  apigateway:
    network_mode: host
    container_name: api-gateway
    build: ../api-gateway
    command: yarn dev
    volumes:
      - ../api-gateway:/usr/app/
      - /usr/app/node_modules
    ports:
      - "3000:3000"
      
  admin:
    network_mode: host
    container_name: admin
    build: ../admin
    command: yarn dev
    environment:
      - PORT=8081
      - NODE_ENV=develop
    volumes:
      - ../admin:/usr/app/
      - /usr/app/node_modules
    ports:
      - "8081:8081"    
    depends_on:
      - apigateway
      - website 
   
